FROM node:18
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./yarn.lock ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g && yarn install
WORKDIR /opt/app
COPY ./ .
RUN yarn add strapi-advanced-uuid
RUN yarn add @strapi/plugin-color-picker
RUN yarn add @strapi/plugin-graphql
RUN yarn add @creazy231/strapi-plugin-apollo-sandbox
RUN yarn build
EXPOSE 1338
CMD ["yarn", "start"]