name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.9.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn
        working-directory: ./backend

      - name: Build strapi admin panel
        run: yarn build
        working-directory: ./backend

      - name: Build Docker image
        run: docker build -t my-app ./backend

      - name: Run Docker image
        run: docker run -d -p 1337:1337 my-app

      - name: Wait for Docker container to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:1337; then
              break
            else
              echo "Waiting for Docker container..."
              sleep 5
            fi
          done

      - name: Test Docker image
        run: curl -f http://localhost:1337
