name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18.9.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cd into backend directory
        run: cd ./backend


      - name: Install dependencies
        run: yarn

      - name: Build strapi admin panel
        run: yarn build