name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.9.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Create .env file
        run: |
          echo DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_PORT=5432 >> $GITHUB_WORKSPACE/backend/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> $GITHUB_WORKSPACE/backend/.env
          echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> $GITHUB_WORKSPACE/backend/.env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> $GITHUB_WORKSPACE/backend/.env
          cat $GITHUB_WORKSPACE/backend/.env
        

      - name: Install dependencies
        run: yarn
        working-directory: ./backend

#      - name: Build strapi admin panel
#        run: yarn build
#        working-directory: ./backend

#      - name: Build Docker image
#        run: docker build -t my-app ./backend

      - name: Run Docker container
        run: docker compose -f ./docker-compose.yml up -d --build

      - name: Check Docker container is running
        run: docker ps

      - name: Wait for Docker container to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:1337; then
              break
            else
              echo "Waiting for Docker container..."
              sleep 5
            fi
          done

      - name: Test Docker image
        run: curl -f http://localhost:1337/
