name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: yarn install
        working-directory: ./frontend

      - name: lint
        run: yarn lint
        working-directory: ./frontend

      - name: build
        run: yarn build
        working-directory: ./frontend

      - name: Test Frontend build
        run: ls frontend/.next

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: front@${{ github.ref }}
          release_name: Release front@${{ github.ref }}
          body: |
            front@${{ github.ref }}
          draft: false
          prerelease: false 
