name: TEST CI APP COMPLETE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.9.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Create .env file
        run: |
          echo DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_PORT=5432 >> $GITHUB_WORKSPACE/backend/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> $GITHUB_WORKSPACE/backend/.env
          echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} >> $GITHUB_WORKSPACE/backend/.env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> $GITHUB_WORKSPACE/backend/.env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> $GITHUB_WORKSPACE/backend/.env
          cat $GITHUB_WORKSPACE/backend/.env


      - name: Install dependencies
        run: yarn
        working-directory: ./backend

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
        env:
          DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PORT: 5432
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          NODE_ENV: ${{ secrets.NODE_ENV }}